#include "visualLB.h"
#include "helper.h"
#include "LBDefinitions.h"
#include <math.h>
#include "computeCellValues.h"

void writeVtkOutput(const double * const collideField, const unsigned int * const flagField,
                    const char* filename, int t, dimensions dim, double* vel){
    
    int x, y, z; //Indices for x, y, z and velocity respectively
   // int i; // commented, because unused
   // int Q = 19;
    //double density;
   // double velocity[3];
  //  const double* currentCell;
    int xl = dim.xlen+2;
    int xlyl = xl*(dim.ylen+2);
    int idx;

    // Open File
    char szFileName[256];
    FILE *fp=NULL;
    sprintf( szFileName, "Output/Out_%i.vtk", t);
    fp = fopen( szFileName, "w");
    if( fp == NULL ){
        char szBuff[256];
        sprintf( szBuff, "Failed to open %s", szFileName);
        ERROR( szBuff );
        return;
    }
    
    // Write Header and Coordinates
    write_vtkHeader(fp, dim);
    write_vtkPointCoordinates(fp, dim);
    
    // Write Velocities
    fprintf(fp, "\nPOINT_DATA %i \n", dim.xlen*dim.ylen*dim.zlen);
    fprintf(fp,"\n");
    fprintf(fp, "VECTORS velocity float\n");
    
    for(z = 1; z <= dim.zlen; z++){
        for(y = 1; y <= dim.ylen; y++) {
            for(x = 1; x <= dim.zlen; x++) {
                idx = (z*xlyl + y*xl + x);

                    fprintf(fp, "%f %f %f\n", vel[3*idx+0], vel[3*idx+1], vel[3*idx+2] );

            }
        }
    }
    
    // Close File
    if( fclose(fp) )
    {
        char szBuff[80];
        sprintf( szBuff, "Failed to close %s", szFileName );
        ERROR( szBuff );
    }
    
}
        
void write_vtkHeader( FILE *fp, dimensions dim) {
    if( fp == NULL )		       
    {
        char szBuff[80];
        sprintf( szBuff, "Null pointer in write_vtkHeader" );
        ERROR( szBuff );
        return;
    }
    
    fprintf(fp,"# vtk DataFile Version 2.0\n");
    fprintf(fp,"generated by CFD-lab course output\n");
    fprintf(fp,"ASCII\n");
    fprintf(fp,"\n");	
    fprintf(fp,"DATASET STRUCTURED_GRID\n");
    fprintf(fp,"DIMENSIONS  %i %i %i \n", dim.xlen, dim.ylen, dim.zlen);
    fprintf(fp,"POINTS %i int\n", (dim.xlen)*(dim.ylen)*(dim.zlen) );
    fprintf(fp,"\n");
}

void write_vtkPointCoordinates( FILE *fp, dimensions dim) {

    int x, y, z;
    for(z = 1; z <= dim.zlen; z++){
        for(y = 1; y <= dim.ylen; y++) {
            for(x = 1; x <= dim.xlen; x++) {
                fprintf(fp, "%i %i %i\n", x, y, z );
            }
        }
    }
}
